In [1]:
import numpy as np

**Task 1**

# Завдання 1. Вектор 10-ти чисел

In [5]:
vector1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(vector1)

[ 1  2  3  4  5  6  7  8  9 10]


# Завдання 2. Матриця з нулями 3х3

In [6]:
matrix1 = np.zeros((3, 3), dtype=int)
print(matrix1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Завдання 3. Матриця 5х5 з випадковими числами

In [7]:
matrix2 = np.random.randint(1, 10, (5, 5))
print(matrix2)

[[6 4 1 1 7]
 [9 1 1 3 5]
 [2 4 7 8 6]
 [6 5 4 5 1]
 [5 4 4 9 8]]


# Завдання 4. Матриця 4х4 з дійсними числами


In [9]:
matrix3 = np.random.rand(4, 4)
print(matrix3)

[[0.18241469 0.96646527 0.51185311 0.21421164]
 [0.42661042 0.51672819 0.9649982  0.29556091]
 [0.92788255 0.6704889  0.62341412 0.04736017]
 [0.73120372 0.34229912 0.46783834 0.16013448]]


# Завдання 5. Операції з одновимірними масивами

In [15]:
vector2a = np.random.randint(1, 10, 5)
vector2b = np.random.randint(1, 10, 5)
print(vector2a + vector2b)
print(vector2a - vector2b)
print(vector2a * vector2b)

[12  8  8  6  9]
[-4 -4 -4  0 -5]
[32 12 12  9 14]


# Завдання 6. Скалярний добуток 


In [16]:
vector3a = np.random.rand(7)
vector3b = np.random.rand(7)
print(np.dot(vector3a, vector3b))

2.0748205036376395


# Завдання 7. Множення матриць 2х2 і 2х3

In [17]:
matrix4a = np.random.randint(1, 10, (2, 2))
matrix4b = np.random.randint(1, 10, (2, 3))
print(np.dot(matrix4a, matrix4b))

[[ 80 112  60]
 [ 10  14   8]]


# Завдання 8. Обернена матриця до матриці 3х3


In [18]:
matrix5 = np.random.randint(1, 10, (3, 3))
inversion = np.linalg.inv(matrix5)
print(inversion)

[[ 0.11111111 -0.22222222  0.11111111]
 [-0.16049383  0.24691358  0.02469136]
 [ 0.0617284   0.13580247 -0.08641975]]


# Завдання 9. Транспонування матриці 4х4

In [20]:
matrix6 = np.random.rand(4, 4)
matrixT = matrix6.T
print(matrixT)

[[0.61517245 0.62411135 0.70572472 0.30545747]
 [0.07387695 0.82153628 0.77839007 0.7038085 ]
 [0.16782869 0.32166734 0.14330273 0.61348711]
 [0.85066091 0.2903563  0.87334127 0.37766542]]


# Завдання 10. Множення матриці 3х4 на вектор 4

In [21]:
matrix7 = np.random.randint(1, 10, (3, 4))
vector4 = np.random.randint(1, 10, 4)
print(matrix7 * vector4)

[[ 4 24  4 72]
 [ 6 54 12 16]
 [ 2 42 12  8]]


# Завданяя 11. Множення матриці 2х3 на вектор 3

In [22]:
matrix8 = np.random.rand(2, 3)
vector5 = np.random.rand(3)
print(matrix8 * vector5)

[[0.02280127 0.43821172 0.40001552]
 [0.82958346 0.12681661 0.46038093]]


# Завдання 12. Поелементне множення матриць 2х2

In [23]:
matrix9a = np.random.randint(1, 10, (2, 2))
matrix9b = np.random.randint(1, 10, (2, 2))
print(matrix9a * matrix9b)

[[ 2 12]
 [14 40]]


# Завдання 13. Добуток матриць 2х2

In [24]:
matrix10a = np.random.randint(1, 10, (2, 2))
matrix10b = np.random.randint(1, 10, (2, 2))
print(np.dot(matrix10a, matrix10b))

[[56 37]
 [37 50]]


# Завдання 14. Сума елементів матриці 5х5

In [25]:
matrix11 = np.random.randint(1, 100, (5, 5))
print(matrix11.sum())

1143


# Завдання 15. Різниця матриць 4х4

In [26]:
matrix12a = np.random.randint(1, 10, (4, 4))
matrix12b = np.random.randint(1, 10, (4, 4))
print(matrix12a - matrix12b)

[[ 0 -2  0  5]
 [ 5  1  2  3]
 [-2  5  1  7]
 [ 4 -1  5  3]]


# Завдання 16. Вектор-стовпчик суми елемнтів матриці

In [29]:
matrix13 = np.random.rand(3, 3)
element_sum = np.sum(matrix13, axis=1)
vector_column = element_sum.reshape((3, 1))
print(vector_column)

[[1.54809961]
 [0.96473342]
 [1.12223122]]


# Завдання 17. Матриця з квадратами чисел

In [32]:
matrix14 = np.random.randint(1, 10, (3, 4))
print(matrix14 ** 2)

[[64  9 25  9]
 [ 1 16 64 25]
 [ 1 25 81 49]]


# Завдання 18. Квадратний корінь з вектора 

In [33]:
vector6 = np.random.randint(1, 50, 4)
sqrt = np.sqrt(vector6)
print(sqrt)

[5.09901951 4.24264069 3.         2.82842712]


**Task 2**

# Завдання 1. Непарні числа = -1

In [34]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# Завдання 2. 1D-масив у 2D-масив

In [35]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


# Завдання 3. Вертикальні масиви

In [40]:
arr2a = np.array([[1, 2],
                 [3, 4]
                 ])
arr2b = np.array([[5, 6],
                 [7, 8]
                 ])
print(np.vstack((arr2a, arr2b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Завдання 4. Конкатенація 

In [41]:
a = np.array([1,2,3])
part1 = np.repeat(a, 3)
part2 = np.tile(a, 3)
print(np.concatenate((part1, part2)))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# Завдання 5. Спільні елементи

In [42]:
a1 = np.array([1,2,3,2,3,4,3,4,5,6]) 
b1 = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a1, b1))

[2 4]


# Завдання 6. 5 максимальних значень

In [43]:
np.random.seed(100)
a2 = np.random.uniform(1, 50, 20)
print(np.argsort(a2)[::-1][:5])

[15 10  3  7 18]


# Завдання 7. Вилучення NpNan

In [50]:
a3 = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
new_a3 = a3[np.isnan(a3) == False]
print(new_a3)

[1. 2. 3. 5. 6. 7.]


# Завдання 8. Евклідова відстань

In [51]:
a4 = np.array([1, 2, 3, 4, 5])
b2 = np.array([4, 5, 6, 7, 8])
distance = np.sqrt(np.sum((a4 - b2) ** 2))
print(distance)

6.708203932499369


# Завдання 9. Iндекс 5-го повторення

In [52]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
print(np.where(x == 1)[0][4])

8


# Завдання 10. Повторюванні записи

In [ ]:
np.random.seed(100)
a5 = np.random.randint(0, 5, 10)
_, first_indices = np.unique(a5, return_index=True)

result = np.ones(a.shape, dtype=bool)
result[first_indices] = False

print(result)